file(GLOB shaders "${CMAKE_CURRENT_SOURCE_DIR}/ShaderFiles/*")
foreach(shader ${shaders})
    get_filename_component(outputFileName ${shader} NAME)
    configure_file(${shader} ${CMAKE_CURRENT_BINARY_DIR}/ShaderFiles/${outputFileName} COPYONLY)
endforeach()